version: "3"
services:
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "1234:1234"
  server:
    build: ./server
    depends_on:
      - db
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/test-db
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
