version: "3"
services:
  client:
    build: ./client
    depends_on:
      - server
    ports:
      - "1234:1234"
  db:
    image: postgres:10.4
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: "always"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
  server:
    build: ./server
    depends_on:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test-db
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      NODE_ENV: development
      PORT: 3000
    ports:
      - "3000:3000"
    command: ["./wait-for-it.sh", "db:5432", "--", "pm2-runtime", "server.js"]